
from __future__ import annotations

import io
import json
import zipfile

import numpy as np
import pandas as pd
import plotly.express as px
import streamlit as st

from src.simulator import CryptoSimulator, AGENT_BEHAVIOURS
from src.graphs import build_graph, network_figure, network_summary
from src.modeling import evaluate_model


st.set_page_config(
    page_title="Crypto Transaction Simulator",
    page_icon="🔷",
    layout="wide",
)

st.markdown(
    """
    <style>
      .block-container {padding-top: 1.2rem; padding-bottom: 2rem;}
      div[data-testid="stMetric"] {
        background: #f8fafc;
        border: 1px solid #e2e8f0;
        border-radius: 14px;
        padding: 12px;
      }
      .role-card {
        border: 1px solid #e2e8f0;
        border-radius: 14px;
        padding: 14px;
        min-height: 210px;
        background: white;
      }
      .small-note {color:#64748b; font-size:0.9rem;}
    </style>
    """,
    unsafe_allow_html=True,
)

if "transactions" not in st.session_state:
    st.session_state.transactions = pd.DataFrame()
    st.session_state.wallets = pd.DataFrame()
    st.session_state.scenarios = pd.DataFrame()
    st.session_state.model_result = None
    st.session_state.last_config = None


def have_data():
    return not st.session_state.transactions.empty


def make_download_zip():
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr(
            "transactions.csv",
            st.session_state.transactions.to_csv(index=False),
        )
        z.writestr(
            "wallets.csv",
            st.session_state.wallets.to_csv(index=False),
        )
        z.writestr(
            "scenarios.csv",
            st.session_state.scenarios.to_csv(index=False),
        )
        z.writestr(
            "simulation_config.json",
            json.dumps(st.session_state.last_config or {}, indent=2),
        )
        z.writestr(
            "README.txt",
            "Generated by Crypto Transaction Simulator V1.\n"
            "Simulation provenance columns such as behaviour and agent type are "
            "for audit/EDA and should not be used as ML predictors.\n",
        )
    buf.seek(0)
    return buf.getvalue()


st.title("🔷 Crypto Transaction Simulator")
st.caption("Multi-agent simulation for synthetic cryptocurrency transaction data")

page = st.sidebar.radio(
    "Navigation",
    ["Simulation", "Transactions", "Network Graph", "EDA", "Modelling", "Download Data", "About"],
)

if page == "Simulation":
    st.subheader("1. Simulation Setup")
    c1, c2 = st.columns([0.9, 1.7])

    with c1:
        n_transactions = st.number_input("Number of transactions", 200, 20000, 1000, step=100)
        duration_days = st.number_input("Simulation duration (days)", 1, 365, 30)
        seed = st.number_input("Random seed", 1, 999999, 42)

        st.markdown("#### Number of agents")
        normal_users = st.number_input("Normal Users", 2, 100, 10)
        merchants = st.number_input("Merchants", 1, 30, 3)
        exchanges = st.number_input("Exchange", 1, 10, 1)
        scammers = st.number_input("Scammer", 1, 20, 1)
        money_launderers = st.number_input("Money Launderer", 1, 20, 2)

    with c2:
        st.markdown("### 2. Agent Behaviours")
        st.caption("These are the actions each agent type can perform in Version 1.")
        cols = st.columns(5)
        role_emoji = {
            "Normal User": "👤", "Merchant": "🏪", "Exchange": "🏦",
            "Scammer": "🎭", "Money Launderer": "🕵️"
        }
        for col, role in zip(cols, AGENT_BEHAVIOURS):
            pretty = {
                "send_receive": "Send / Receive",
                "payment": "Payments",
                "daily_transaction": "Daily transactions",
                "accept_payment": "Accept payments",
                "refund": "Refunds",
                "issue_invoice": "Issue invoices",
                "deposit": "Deposits",
                "withdrawal": "Withdrawals",
                "wallet_creation": "Wallet creation",
                "fake_wallet": "Fake wallets",
                "rug_pull": "Rug pull",
                "phishing": "Phishing",
                "wallet_hopping": "Wallet hopping",
                "chain_peeling": "Chain peeling",
                "mixer_interaction": "Mixer interaction",
                "smurfing": "Smurfing",
            }
            items = "".join(f"<li>{pretty[x]}</li>" for x in AGENT_BEHAVIOURS[role])
            col.markdown(
                f"<div class='role-card'><h3>{role_emoji[role]} {role}</h3>"
                f"<ul>{items}</ul></div>",
                unsafe_allow_html=True,
            )

        st.info(
            "V1 research note: this is a transparent agent-based behavioural simulator. "
            "It does not falsely claim PPO yet. The end-to-end data, EDA and modelling "
            "pipeline is working; a real PPO/MARL decision policy can replace the V1 "
            "behaviour-selection policy in the next version."
        )

        if st.button("▶ Run Simulation", type="primary", use_container_width=True):
            cfg = {
                "n_transactions": int(n_transactions),
                "duration_days": int(duration_days),
                "normal_users": int(normal_users),
                "merchants": int(merchants),
                "exchanges": int(exchanges),
                "scammers": int(scammers),
                "money_launderers": int(money_launderers),
                "seed": int(seed),
            }
            with st.spinner("Generating synthetic transaction ecosystem..."):
                sim = CryptoSimulator(**cfg)
                tx, wallets, scenarios = sim.run()
                st.session_state.transactions = tx
                st.session_state.wallets = wallets
                st.session_state.scenarios = scenarios
                st.session_state.last_config = cfg
                st.session_state.model_result = None
            st.success(f"Generated {len(tx):,} transactions.")

    if have_data():
        st.divider()
        st.subheader("Transaction Overview")
        tx = st.session_state.transactions
        m1, m2, m3, m4 = st.columns(4)
        m1.metric("Total Transactions", f"{len(tx):,}")
        m2.metric("Genuine", f"{(tx.fraud_label == 0).sum():,}")
        m3.metric("Fraud", f"{(tx.fraud_label == 1).sum():,}")
        m4.metric("Wallets", f"{len(st.session_state.wallets):,}")

        f1, f2 = st.columns(2)
        with f1:
            counts = tx["label"].value_counts().rename_axis("Label").reset_index(name="Transactions")
            st.plotly_chart(px.pie(counts, names="Label", values="Transactions", hole=0.55,
                                   title="Fraud vs Genuine"), use_container_width=True)
        with f2:
            role_counts = tx["initiating_agent_type"].value_counts().rename_axis("Agent").reset_index(name="Transactions")
            st.plotly_chart(px.bar(role_counts, x="Agent", y="Transactions",
                                   title="Transactions by Initiating Agent Type"), use_container_width=True)

elif page == "Transactions":
    st.subheader("Generated Transactions")
    if not have_data():
        st.warning("Run a simulation first.")
    else:
        tx = st.session_state.transactions.copy()
        q = st.text_input("Filter by wallet, behaviour, scenario or label")
        if q:
            mask = tx.astype(str).apply(lambda col: col.str.contains(q, case=False, regex=False)).any(axis=1)
            tx = tx[mask]
        st.dataframe(tx, use_container_width=True, height=590)
        st.caption(
            "Columns such as initiating_agent_type, behaviour, scenario_id and label are "
            "simulation ground truth/provenance. They are excluded from model features."
        )

elif page == "Network Graph":
    st.subheader("Transaction Network Graph")
    if not have_data():
        st.warning("Run a simulation first.")
    else:
        G = build_graph(st.session_state.transactions, st.session_state.wallets)
        summary = network_summary(G)
        a, b, c, d = st.columns(4)
        a.metric("Wallet Nodes", summary["nodes"])
        b.metric("Relationship Edges", summary["edges"])
        c.metric("Graph Density", f'{summary["density"]:.4f}')
        d.metric("Average Degree", f'{summary["avg_degree"]:.2f}')

        st.markdown(
            "**Node color:** blue = legitimate agent, red = malicious agent, grey = external service. "
            "**Node shape:** distinguishes Normal User, Merchant, Exchange, Scammer and Money Launderer. "
            "Red edges have at least one fraud-labelled transaction."
        )
        st.plotly_chart(network_figure(G), use_container_width=True)

elif page == "EDA":
    st.subheader("Exploratory Data Analysis")
    if not have_data():
        st.warning("Run a simulation first.")
    else:
        tx = st.session_state.transactions.copy()

        a, b, c, d = st.columns(4)
        a.metric("Rows", f"{len(tx):,}")
        b.metric("Fraud rate", f"{tx.fraud_label.mean()*100:.1f}%")
        c.metric("Median amount", f"{tx.amount_btc.median():.4f} BTC")
        d.metric("Median time gap", f"{tx.time_since_last_tx_seconds.median():.0f} sec")

        c1, c2 = st.columns(2)
        with c1:
            st.plotly_chart(
                px.histogram(tx, x="amount_btc", color="label", nbins=50,
                             title="Transaction Amount Distribution", barmode="overlay"),
                use_container_width=True,
            )
        with c2:
            bdf = tx["behaviour"].value_counts().rename_axis("Behaviour").reset_index(name="Transactions")
            st.plotly_chart(px.bar(bdf, x="Behaviour", y="Transactions",
                                   title="Transactions by Behaviour"), use_container_width=True)

        daily = (
            tx.assign(date=pd.to_datetime(tx.timestamp).dt.date)
              .groupby(["date", "label"]).size().reset_index(name="Transactions")
        )
        st.plotly_chart(
            px.line(daily, x="date", y="Transactions", color="label",
                    title="Transactions Over Time"),
            use_container_width=True,
        )

        numeric_cols = [
            "amount_btc", "transaction_fee_btc", "sender_wallet_age_days",
            "receiver_wallet_age_days", "sender_tx_count_before",
            "receiver_tx_count_before", "sender_unique_counterparties_before",
            "receiver_unique_counterparties_before", "time_since_last_tx_seconds",
            "fraud_label",
        ]
        corr = tx[numeric_cols].corr(numeric_only=True)
        st.plotly_chart(
            px.imshow(corr, text_auto=".2f", aspect="auto",
                      title="Numeric Feature Correlation"),
            use_container_width=True,
        )

        st.markdown("### Wallet activity")
        wallets = st.session_state.wallets.sort_values("transaction_count", ascending=False)
        st.dataframe(wallets.head(25), use_container_width=True)

elif page == "Modelling":
    st.subheader("Fraud Detection Modelling")
    if not have_data():
        st.warning("Run a simulation first.")
    else:
        st.warning(
            "Leakage protection is enabled. Agent type, behaviour, scenario ID, label, "
            "wallet IDs and transaction type are NOT used as predictors."
        )
        c1, c2 = st.columns(2)
        with c1:
            model_name = st.selectbox(
                "Model",
                ["Logistic Regression", "Random Forest", "XGBoost"],
            )
        with c2:
            split_mode = st.selectbox(
                "70/15/15 split",
                ["Temporal", "Stratified random"],
                help="Temporal is more realistic for time-ordered fraud evaluation.",
            )

        if st.button("Train & Evaluate Model", type="primary"):
            try:
                with st.spinner("Training model in the cloud session..."):
                    result = evaluate_model(model_name, st.session_state.transactions, split_mode)
                    st.session_state.model_result = (model_name, split_mode, result)
            except Exception as e:
                st.error(str(e))

        if st.session_state.model_result:
            model_name, split_mode, result = st.session_state.model_result
            st.markdown(f"### Results — {model_name}")
            metrics = result["metrics"]
            cols = st.columns(6)
            for col, (name, value) in zip(cols, metrics.items()):
                col.metric(name, "N/A" if pd.isna(value) else f"{value:.3f}")

            st.caption(
                f"Split sizes — train: {result['sizes']['train']:,}, "
                f"validation: {result['sizes']['validation']:,}, "
                f"test: {result['sizes']['test']:,}"
            )

            cm = result["confusion_matrix"]
            cm_df = pd.DataFrame(
                cm,
                index=["Actual Genuine", "Actual Fraud"],
                columns=["Pred Genuine", "Pred Fraud"],
            )
            c1, c2 = st.columns(2)
            with c1:
                st.plotly_chart(
                    px.imshow(cm_df, text_auto=True, title="Confusion Matrix", aspect="auto"),
                    use_container_width=True,
                )
            with c2:
                if result["importance"] is not None:
                    imp = result["importance"].head(12).sort_values("importance")
                    st.plotly_chart(
                        px.bar(imp, x="importance", y="feature", orientation="h",
                               title="Feature Importance / Magnitude"),
                        use_container_width=True,
                    )

elif page == "Download Data":
    st.subheader("Download Generated Dataset")
    if not have_data():
        st.warning("Run a simulation first.")
    else:
        st.write(
            "The ZIP contains transactions.csv, wallets.csv, scenarios.csv and the simulation configuration."
        )
        st.download_button(
            "⬇ Download generated dataset ZIP",
            data=make_download_zip(),
            file_name="synthetic_crypto_dataset.zip",
            mime="application/zip",
            type="primary",
        )
        st.download_button(
            "Download transactions.csv",
            data=st.session_state.transactions.to_csv(index=False),
            file_name="transactions.csv",
            mime="text/csv",
        )

elif page == "About":
    st.subheader("About Version 1")
    st.markdown(
        """
        This prototype implements the **Approach 2 synthetic-data workflow** as a browser dashboard:

        1. Configure the five agent types.
        2. Generate genuine and fraudulent synthetic cryptocurrency transactions.
        3. Inspect transactions and wallet relationships.
        4. Explore the generated data with EDA.
        5. Train baseline fraud-detection models without using ground-truth/provenance fields as predictors.
        6. Download the generated dataset.

        **Five agent types:** Normal User, Merchant, Exchange, Scammer, Money Launderer.

        **Research limitation:** V1 uses a transparent behaviour-selection policy. It is intentionally
        not labelled as PPO. A genuine PPO/MARL decision layer should be implemented and evaluated
        as a separate research step, then plugged into the same simulation interface.
        """
    )
