from __future__ import annotations

import io
import json
import zipfile

import pandas as pd
import plotly.express as px
import streamlit as st

from src.simulator import CryptoSimulator
from src.graphs import (
    build_graph,
    network_figure,
    network_summary,
    node_relationship_analysis,
    neighborhood_figure,
)
from src.modeling import evaluate_model
from src.storage import load_latest_run, save_latest_run


st.set_page_config(
    page_title="Crypto Transaction Simulator",
    page_icon="🔷",
    layout="wide",
)

st.markdown(
    """
    <style>
      .block-container {padding-top: 1.2rem; padding-bottom: 2rem;}
      div[data-testid="stMetric"] {
        background: #f8fafc;
        border: 1px solid #e2e8f0;
        border-radius: 14px;
        padding: 12px;
      }
      section[data-testid="stSidebar"] div.stButton > button {
        border-radius: 10px;
        min-height: 44px;
        font-weight: 600;
        text-align: left;
      }
      .small-note {color:#64748b; font-size:0.9rem;}
    </style>
    """,
    unsafe_allow_html=True,
)

# ---------------- Session state + restore after normal refresh ----------------
for key, default in {
    "transactions": pd.DataFrame(),
    "wallets": pd.DataFrame(),
    "scenarios": pd.DataFrame(),
    "model_result": None,
    "last_config": None,
    "page": "Simulation",
}.items():
    if key not in st.session_state:
        st.session_state[key] = default

if st.session_state.transactions.empty:
    restored = load_latest_run()
    if restored is not None:
        tx, wallets, scenarios, config = restored
        st.session_state.transactions = tx
        st.session_state.wallets = wallets
        st.session_state.scenarios = scenarios
        st.session_state.last_config = config


def have_data():
    return not st.session_state.transactions.empty


def make_download_zip():
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("transactions.csv", st.session_state.transactions.to_csv(index=False))
        z.writestr("wallets.csv", st.session_state.wallets.to_csv(index=False))
        z.writestr("scenarios.csv", st.session_state.scenarios.to_csv(index=False))
        z.writestr(
            "simulation_config.json",
            json.dumps(st.session_state.last_config or {}, indent=2),
        )
        z.writestr(
            "README.txt",
            "Generated by Crypto Transaction Simulator V1.1.\n"
            "Ground-truth/provenance fields are retained for audit and EDA, "
            "but excluded from ML predictors.\n",
        )
    buf.seek(0)
    return buf.getvalue()


def nav_button(label: str, icon: str):
    active = st.session_state.page == label
    if st.sidebar.button(
        f"{icon}  {label}",
        key=f"nav_{label}",
        use_container_width=True,
        type="primary" if active else "secondary",
    ):
        st.session_state.page = label
        st.rerun()


st.title("🔷 Crypto Transaction Simulator")
st.caption("Multi-agent simulation for synthetic cryptocurrency transaction data")

st.sidebar.markdown("### Navigation")
nav_button("Simulation", "▶")
nav_button("Network Graph", "🕸️")
nav_button("EDA", "📊")
nav_button("Modelling", "🧠")
st.sidebar.divider()
if have_data():
    st.sidebar.success(f"Dataset loaded: {len(st.session_state.transactions):,} transactions")
else:
    st.sidebar.info("No dataset generated yet.")

page = st.session_state.page


# ===================== SIMULATION =====================
if page == "Simulation":
    st.subheader("1. Simulation Setup")

    c1, c2, c3 = st.columns(3)
    with c1:
        n_transactions = st.number_input(
            "Number of transactions", 200, 20000,
            int((st.session_state.last_config or {}).get("n_transactions", 1000)),
            step=100,
        )
        duration_days = st.number_input(
            "Simulation duration (days)", 1, 365,
            int((st.session_state.last_config or {}).get("duration_days", 30)),
        )
        seed = st.number_input(
            "Random seed", 1, 999999,
            int((st.session_state.last_config or {}).get("seed", 42)),
        )

    with c2:
        st.markdown("#### Legitimate agents")
        normal_users = st.number_input(
            "Normal Users", 2, 100,
            int((st.session_state.last_config or {}).get("normal_users", 10)),
        )
        merchants = st.number_input(
            "Merchants", 1, 30,
            int((st.session_state.last_config or {}).get("merchants", 3)),
        )
        exchanges = st.number_input(
            "Exchange", 1, 10,
            int((st.session_state.last_config or {}).get("exchanges", 1)),
        )

    with c3:
        st.markdown("#### Fraud-related agents")
        scammers = st.number_input(
            "Scammer", 1, 20,
            int((st.session_state.last_config or {}).get("scammers", 1)),
        )
        money_launderers = st.number_input(
            "Money Launderer", 1, 20,
            int((st.session_state.last_config or {}).get("money_launderers", 2)),
        )

    button_label = "▶ Run Simulation" if not have_data() else "↻ Run New Simulation (replace current dataset)"
    if st.button(button_label, type="primary", use_container_width=True):
        cfg = {
            "n_transactions": int(n_transactions),
            "duration_days": int(duration_days),
            "normal_users": int(normal_users),
            "merchants": int(merchants),
            "exchanges": int(exchanges),
            "scammers": int(scammers),
            "money_launderers": int(money_launderers),
            "seed": int(seed),
        }

        with st.spinner("Generating synthetic transaction ecosystem..."):
            sim = CryptoSimulator(**cfg)
            tx, wallets, scenarios = sim.run()

            st.session_state.transactions = tx
            st.session_state.wallets = wallets
            st.session_state.scenarios = scenarios
            st.session_state.last_config = cfg
            st.session_state.model_result = None

            save_latest_run(tx, wallets, scenarios, cfg)

        st.success(
            f"Generated {len(tx):,} transactions. This run is retained for page navigation and normal browser refreshes."
        )

    if have_data():
        tx = st.session_state.transactions

        st.divider()
        st.subheader("2. Generated Dataset")

        m1, m2, m3, m4 = st.columns(4)
        m1.metric("Total Transactions", f"{len(tx):,}")
        m2.metric("Genuine", f"{(tx.fraud_label == 0).sum():,}")
        m3.metric("Fraud", f"{(tx.fraud_label == 1).sum():,}")
        m4.metric("Wallets", f"{len(st.session_state.wallets):,}")

        d1, d2 = st.columns([1, 3])
        with d1:
            st.download_button(
                "⬇ Download Dataset ZIP",
                data=make_download_zip(),
                file_name="synthetic_crypto_dataset.zip",
                mime="application/zip",
                type="primary",
                use_container_width=True,
            )
        with d2:
            st.caption(
                "Contains transactions.csv, wallets.csv, scenarios.csv and the simulation configuration."
            )

        st.markdown("### Transaction Table")
        st.dataframe(tx, use_container_width=True, height=520)

        st.markdown("### Agent / Wallet Table")
        st.caption(
            "Shows the wallet identity, owning agent, agent type, age, balances, transaction count and unique counterparties."
        )
        st.dataframe(
            st.session_state.wallets.sort_values("transaction_count", ascending=False),
            use_container_width=True,
            height=380,
        )

        with st.expander("Scenario / ground-truth table"):
            st.dataframe(st.session_state.scenarios, use_container_width=True, height=300)

        st.caption(
            "Simulation provenance such as agent type, behaviour, scenario ID and labels is available "
            "for audit/EDA, but those fields are excluded from the fraud-detection model predictors."
        )


# ===================== NETWORK GRAPH =====================
elif page == "Network Graph":
    st.subheader("Transaction Network Graph")

    if not have_data():
        st.warning("Run a simulation first.")
    else:
        tx = st.session_state.transactions
        G = build_graph(tx, st.session_state.wallets)
        summary = network_summary(G)

        a, b, c, d = st.columns(4)
        a.metric("Wallet Nodes", summary["nodes"])
        b.metric("Relationship Edges", summary["edges"])
        c.metric("Graph Density", f'{summary["density"]:.4f}')
        d.metric("Average Degree", f'{summary["avg_degree"]:.2f}')

        st.info(
            "Blue nodes = genuine agent wallets. Red nodes = fraud-related agent/service wallets. "
            "All nodes use the same shape. Click a node to inspect its relationships and pattern indicators."
        )

        event = st.plotly_chart(
            network_figure(G),
            use_container_width=True,
            key="interactive_network",
            on_select="rerun",
            selection_mode="points",
            config={"scrollZoom": True, "displaylogo": False},
        )

        selected_node = None
        try:
            for p in event.selection.points:
                custom = p.get("customdata")
                if custom and isinstance(custom, (list, tuple)) and len(custom) >= 1:
                    selected_node = custom[0]
                    break
        except Exception:
            selected_node = None

        st.divider()
        st.markdown("### Selected Node Relationship Explorer")

        if not selected_node:
            st.caption("Click a blue or red node in the graph above.")
        else:
            info = node_relationship_analysis(selected_node, tx, G)

            st.markdown(f"#### {selected_node}")
            k1, k2, k3, k4, k5 = st.columns(5)
            k1.metric("Agent Type", info["agent_type"])
            k2.metric("Status", info["fraud_status"])
            k3.metric("Incoming", info["in_degree"])
            k4.metric("Outgoing", info["out_degree"])
            k5.metric("Connected Wallets", len(set(info["predecessors"] + info["successors"])))

            left, right = st.columns([1.15, 1])
            with left:
                st.plotly_chart(
                    neighborhood_figure(selected_node, G),
                    use_container_width=True,
                    config={"displaylogo": False},
                )
            with right:
                st.markdown("##### Relationship / network pattern indicators")
                if info["indicators"]:
                    for indicator in info["indicators"]:
                        st.write(f"• {indicator}")
                else:
                    st.write("No strong relationship indicator was detected for this node.")

                if info["behaviours"]:
                    st.markdown("##### Simulator ground-truth behaviours involving this node")
                    behaviour_df = pd.DataFrame(
                        [
                            {"Behaviour": k, "Fraud-labelled transactions": v}
                            for k, v in info["behaviours"].items()
                        ]
                    )
                    st.dataframe(behaviour_df, hide_index=True, use_container_width=True)

                st.caption(
                    "Pattern indicators are descriptive graph signals, not independent proof of real-world fraud. "
                    "The synthetic simulator's ground truth is displayed separately."
                )

            st.markdown("##### Direct relationships")
            if info["relationship_table"].empty:
                st.write("No direct relationships.")
            else:
                st.dataframe(
                    info["relationship_table"],
                    hide_index=True,
                    use_container_width=True,
                    height=300,
                )

            with st.expander("Transactions involving this selected node"):
                st.dataframe(info["transactions"], use_container_width=True, height=360)


# ===================== EDA =====================
elif page == "EDA":
    st.subheader("Exploratory Data Analysis")

    if not have_data():
        st.warning("Run a simulation first.")
    else:
        tx = st.session_state.transactions.copy()

        a, b, c, d = st.columns(4)
        a.metric("Rows", f"{len(tx):,}")
        b.metric("Fraud rate", f"{tx.fraud_label.mean()*100:.1f}%")
        c.metric("Median amount", f"{tx.amount_btc.median():.4f} BTC")
        d.metric("Median time gap", f"{tx.time_since_last_tx_seconds.median():.0f} sec")

        c1, c2 = st.columns(2)
        with c1:
            st.plotly_chart(
                px.histogram(
                    tx, x="amount_btc", color="label", nbins=50,
                    title="Transaction Amount Distribution", barmode="overlay",
                ),
                use_container_width=True,
            )
        with c2:
            bdf = tx["behaviour"].value_counts().rename_axis("Behaviour").reset_index(name="Transactions")
            st.plotly_chart(
                px.bar(bdf, x="Behaviour", y="Transactions", title="Transactions by Behaviour"),
                use_container_width=True,
            )

        daily = (
            tx.assign(date=pd.to_datetime(tx.timestamp).dt.date)
              .groupby(["date", "label"]).size().reset_index(name="Transactions")
        )
        st.plotly_chart(
            px.line(daily, x="date", y="Transactions", color="label", title="Transactions Over Time"),
            use_container_width=True,
        )

        numeric_cols = [
            "amount_btc", "transaction_fee_btc", "sender_wallet_age_days",
            "receiver_wallet_age_days", "sender_tx_count_before",
            "receiver_tx_count_before", "sender_unique_counterparties_before",
            "receiver_unique_counterparties_before", "time_since_last_tx_seconds",
            "fraud_label",
        ]
        corr = tx[numeric_cols].corr(numeric_only=True)
        st.plotly_chart(
            px.imshow(corr, text_auto=".2f", aspect="auto", title="Numeric Feature Correlation"),
            use_container_width=True,
        )

        st.markdown("### Wallet activity")
        st.dataframe(
            st.session_state.wallets.sort_values("transaction_count", ascending=False).head(25),
            use_container_width=True,
        )


# ===================== MODELLING =====================
elif page == "Modelling":
    st.subheader("Fraud Detection Modelling")

    if not have_data():
        st.warning("Run a simulation first.")
    else:
        st.warning(
            "Leakage protection is enabled. Agent type, behaviour, scenario ID, label, "
            "wallet IDs and transaction type are NOT used as predictors."
        )

        c1, c2 = st.columns(2)
        with c1:
            model_name = st.selectbox(
                "Model",
                ["Logistic Regression", "Random Forest", "XGBoost"],
            )
        with c2:
            split_mode = st.selectbox(
                "70/15/15 split",
                ["Temporal", "Stratified random"],
                help="Temporal is usually more realistic for time-ordered fraud evaluation.",
            )

        if st.button("Train & Evaluate Model", type="primary"):
            try:
                with st.spinner("Training model in the cloud session..."):
                    result = evaluate_model(
                        model_name,
                        st.session_state.transactions,
                        split_mode,
                    )
                    st.session_state.model_result = (model_name, split_mode, result)
            except Exception as e:
                st.error(str(e))

        if st.session_state.model_result:
            model_name, split_mode, result = st.session_state.model_result
            st.markdown(f"### Results — {model_name}")

            metrics = result["metrics"]
            cols = st.columns(6)
            for col, (name, value) in zip(cols, metrics.items()):
                col.metric(name, "N/A" if pd.isna(value) else f"{value:.3f}")

            st.caption(
                f"Split sizes — train: {result['sizes']['train']:,}, "
                f"validation: {result['sizes']['validation']:,}, "
                f"test: {result['sizes']['test']:,}"
            )

            cm = result["confusion_matrix"]
            cm_df = pd.DataFrame(
                cm,
                index=["Actual Genuine", "Actual Fraud"],
                columns=["Pred Genuine", "Pred Fraud"],
            )

            c1, c2 = st.columns(2)
            with c1:
                st.plotly_chart(
                    px.imshow(cm_df, text_auto=True, title="Confusion Matrix", aspect="auto"),
                    use_container_width=True,
                )
            with c2:
                if result["importance"] is not None:
                    imp = result["importance"].head(12).sort_values("importance")
                    st.plotly_chart(
                        px.bar(
                            imp, x="importance", y="feature", orientation="h",
                            title="Feature Importance / Magnitude",
                        ),
                        use_container_width=True,
                    )
